version: '3'
services:
  expresscart:
    image: "node:8"
    build: .
    container_name: "expresscart"
    environment:
      NODE_ENV: development
      NODE_PATH: /
    ports:
      - "1111:1111"
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:3.4.10
    container_name: "expresscart-mongodb"
    volumes:
      - expresscart-mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ec
      MONGO_INITDB_ROOT_PASSWORD: ec
      MONGO_INITDB_DATABASE: expresscart
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null
volumes:
  expresscart-mongo-data: {}
